### ISSUE TITLE
Add new entry

### ISSUE THREAD

**Issue by kraeved88** [sssolutiontec/open-source-catalog#3]
Please note title, description, website, source code, technologies and categories are mandatory.

***Title:**

Name of open source product. This will appear on top of page.

***Description:**

Explain this product, what is work for, benefits etc to under stand others.

***Website(s):**

A Online demo or website about the product for more/detail information.

***Source code(s):**

Location of source code. Can be multiple repos. More detail better it will be. e-g frontend repo & backend repo etc

***Technologies:**

Technologies used to create this product e-g Java, mysql, solr, php etc

***Categories:**

General category, under which we should put this product. In case of multiple categories, please specify the main catagory
under which we should place this product. e-g biology(main), education

**Blog(s):**

Where from you came to know about this product or if any blog explaining about this product

**Tags:**

Tags to help additional search keywords

**Products:**

Other product offer by same vendor which might interest readers.

**Others:**

Any other field you would like to include in this page. e-g fieldname:value

**Comment by rizwan-ishtiaq** [comment]
Nothing specified
